In [75]:
# unos biblioteke.
import numpy as np

In [76]:
# kreiranje počentih listi.
x = [20, 24, 14, 13, 23, 56, 12]
y = [-40, -54, -13, 33, 25, -56, 34]
z = [10, 46, 26, 13, 45, -52, 14]

In [77]:
# pretvorba listi u numpy niz.
podaci = np.vstack([x, y, z])

In [78]:
#prikaz numpy niza.
podaci

array([[ 20,  24,  14,  13,  23,  56,  12],
       [-40, -54, -13,  33,  25, -56,  34],
       [ 10,  46,  26,  13,  45, -52,  14]])

In [79]:
#uklanjanje redaka gdje drugi redak ima negativnu vrijednost. 
podaci = podaci[:, podaci[1] > 0]

In [80]:
# prikaz podataka nakon uklanjanja redaka gdje drugi redak ima negativnu vrijednost.
podaci

array([[13, 23, 12],
       [33, 25, 34],
       [13, 45, 14]])

In [81]:
podaci = podaci.T

In [82]:
# prikaz podataka nakon transponiranja.
podaci

array([[13, 33, 13],
       [23, 25, 45],
       [12, 34, 14]])

In [84]:
# množenje s jediničnom matricom.
podaci * np.identity(3)

array([[13.,  0.,  0.],
       [ 0., 25.,  0.],
       [ 0.,  0., 14.]])