<h1>CATEGORICAL CLASSIFICATION NEURAL NETWORK</h1>

DATA SETUP

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\kundi\Sphere\DataLibrary\NeuralNetwork_Transport\import_data\filtered_data.xlsx') ## Don't forget to relocate the destination to the file on your PC!

In [3]:
df.head(30)

Mode  Gender  Age  Education  Income  Public/Private_Sector  \
0      1       1   32          0    1500                      1   
1      1       0   36          1    3500                      1   
2      2       1   29          1    2500                      1   
3      1       1   35          0    3500                      1   
4      2       0   44          1    2500                      0   
5      2       1   43          1    2500                      0   
6      2       0   30          1    1500                      1   
7      1       0   32          1    7500                      1   
8      1       1   60          1    2500                      0   
9      1       0   38          1    2500                      0   
10     2       1   28          1    3500                      1   
11     2       0   56          0    1500                      1   
12     2       1   47          0    1500                      1   
13     1       1   59          1    5500                      1   
14     1       1   54          0    2500                      1   
15     3       1   32          1    1500                      1   
16     1       1   34          0    1500                      1   
17     2       0   56          1    1500                      1   
18     1       0   26          1    2500                      0   
19     2       0   59          1    1500                      0   
20     3       0   31          0    1500                      1   
21     2       0   40          1    1500                      0   
22     2       0   56          0     900                      1   
23     3       0   56          1    1500                      1   
24     1       1   67          0    3500                      1   
25     2       1   30          1    1500                      1   
26     3       1   26          1    1500                      0   
27     2       0   38          1    2500                      0   
28     1       1   60          1    7500                      0   
29     1       1   44          1    7500                      1   

    Drivers_license  Marital_status  Cars_in_HH  Walk_AV  PublicTransport_AV  \
0                 1               1           2        0                   1   
1                 1               0           1        1                   1   
2                 1               0           2        0                   1   
3                 1               1           1        0                   1   
4                 1               1           1        1                   1   
5                 1               1           1        1                   1   
6                 1               1           1        1                   1   
7                 1               1           2        1                   1   
8                 1               1           4        1                   1   
9                 1               1           1        1                   1   
10                1               0           1        1                   1   
11                0               0           1        0                   1   
12                0               1           0        1                   1   
13                1               1           2        1                   1   
14                1               1           1        0                   1   
15                1               0           1        1                   1   
16                1               1           1        1                   1   
17                1               1           1        1                   1   
18                1               0           1        1                   1   
19                0               0           0        1                   1   
20                0               1           1        1                   1   
21                0               1           2        1                   1   
22                0               1           0        1                   1   
23    

In [4]:
df.head()

Mode  Gender  Age  Education  Income  Public/Private_Sector  \
0     1       1   32          0    1500                      1   
1     1       0   36          1    3500                      1   
2     2       1   29          1    2500                      1   
3     1       1   35          0    3500                      1   
4     2       0   44          1    2500                      0   

   Drivers_license  Marital_status  Cars_in_HH  Walk_AV  PublicTransport_AV  \
0                1               1           2        0                   1   
1                1               0           1        1                   1   
2                1               0           2        0                   1   
3                1               1           1        0                   1   
4                1               1           1        1                   1   

   Car_AV  
0       1  
1       1  
2       1  
3       1  
4       1

0:3 CLASSES FOR KERAS PROCESSING

In [5]:
df['Mode'].replace(1,0,inplace=True)
df['Mode'].replace(2,1,inplace=True)
df['Mode'].replace(3,2,inplace=True)

TRAINING

In [6]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [7]:
x = df.drop(columns = ['Mode'])
y = df['Mode']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

SETTING 3 CLASSES

In [9]:
y_train = to_categorical(y_train, num_classes = 3) ## Convert to categorical
y_test = to_categorical(y_test, num_classes = 3) ## num_classes = 3 because there are 3 different modes of transport

In [10]:
model = tf.keras.models.Sequential() ## Sequential is a linear stack of layers

In [11]:
x_train.shape

(435, 11)

In [12]:
model.add(tf.keras.layers.Dense(256,input_shape = x_train.shape, activation='relu')) 
model.add(tf.keras.layers.Dense(256, activation = 'relu'))
model.add(tf.keras.layers.Dense(256, activation = 'relu'))
model.add(tf.keras.layers.Dense(256, activation = 'relu')) 
model.add(tf.keras.layers.Dense(256, activation = 'relu')) 
model.add(tf.keras.layers.Dense(3, activation='softmax')) ## Softmax is used to convert the output to probabilities, which is what we want for classification problems.

In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs = 300, batch_size = 32)

Epoch 1/300
14/14 [==============================] - 1s 6ms/step - loss: 41.1584 - accuracy: 0.3563
Epoch 2/300
14/14 [==============================] - 0s 6ms/step - loss: 8.1926 - accuracy: 0.3724
Epoch 3/300
14/14 [==============================] - 0s 7ms/step - loss: 5.7671 - accuracy: 0.3609
Epoch 4/300
14/14 [==============================] - 0s 7ms/step - loss: 2.6359 - accuracy: 0.3747
Epoch 5/300
14/14 [==============================] - 0s 7ms/step - loss: 4.7587 - accuracy: 0.3931
Epoch 6/300
14/14 [==============================] - 0s 7ms/step - loss: 3.2375 - accuracy: 0.4023
Epoch 7/300
14/14 [==============================] - 0s 6ms/step - loss: 1.6063 - accuracy: 0.4368
Epoch 8/300
14/14 [==============================] - 0s 7ms/step - loss: 2.1226 - accuracy: 0.4023
Epoch 9/300
14/14 [==============================] - 0s 6ms/step - loss: 2.5129 - accuracy: 0.3954
Epoch 10/300
14/14 [==============================] - 0s 6ms/step - loss: 1.8327 - accuracy: 0.3908
Epoch 11

EVAULATION

In [15]:
model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 3ms/step - loss: 1.0205 - accuracy: 0.4862


[1.0204687118530273, 0.4862385392189026]

In [16]:
import numpy as np

In [17]:
x_test

Gender  Age  Education  Income  Public/Private_Sector  Drivers_license  \
277       0   53          1    2500                      0                1   
521       0   44          1    3500                      1                1   
218       1   41          1     900                      1                1   
173       0   39          1    1500                      0                1   
194       0   26          1    1500                      1                1   
..      ...  ...        ...     ...                    ...              ...   
487       0   53          0    1500                      1                0   
510       1   51          0    2500                      0                1   
325       0   23          1    1500                      1                0   
30        0   48          1    2500                      1                0   
96        0   24          1    1500                      0                1   

     Marital_status  Cars_in_HH  Walk_AV  PublicTransport_AV  Car_AV  
277               0           1        1                   1       1  
521               1           2        0                   1       1  
218               1           1        1                   1       1  
173               1           1        1                   0       1  
194               0           2        1                   1       1  
..              ...         ...      ...                 ...     ...  
487               1           1        1                   1       1  
510               1           1        1                   1       1  
325               0           1        1                   1       1  
30                1           2        1                   1       1  
96                1           1        0                   1       1  

[109 rows x 11 columns]

PREDICTION

In [18]:
prediction = np.round(model.predict(np.array([[x_test.iloc[0]]])))
prediction

array([[[0., 0., 0.]]], dtype=float32)

In [19]:
y_test

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1

In [20]:
x_test.reset_index(inplace=True)

In [21]:
x_test.drop(columns = ['index'], inplace=True)

In [22]:
x_test

Gender  Age  Education  Income  Public/Private_Sector  Drivers_license  \
0         0   53          1    2500                      0                1   
1         0   44          1    3500                      1                1   
2         1   41          1     900                      1                1   
3         0   39          1    1500                      0                1   
4         0   26          1    1500                      1                1   
..      ...  ...        ...     ...                    ...              ...   
104       0   53          0    1500                      1                0   
105       1   51          0    2500                      0                1   
106       0   23          1    1500                      1                0   
107       0   48          1    2500                      1                0   
108       0   24          1    1500                      0                1   

     Marital_status  Cars_in_HH  Walk_AV  PublicTransport_AV  Car_AV  
0                 0           1        1                   1       1  
1                 1           2        0                   1       1  
2                 1           1        1                   1       1  
3                 1           1        1                   0       1  
4                 0           2        1                   1       1  
..              ...         ...      ...                 ...     ...  
104               1           1        1                   1       1  
105               1           1        1                   1       1  
106               0           1        1                   1       1  
107               1           2        1                   1       1  
108               1           1        0                   1       1  

[109 rows x 11 columns]

In [23]:
predicted = np.round(model.predict(x_test))
predicted

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0

In [30]:
actual = pd.DataFrame(y_test)
actual.reset_index(inplace=True)

In [31]:
actual.drop(columns=['index'], inplace=True)

In [79]:
results = actual == predicted

In [80]:
results.replace(True, 'Yes', inplace=True)
results.replace(False, 'No', inplace=True)

In [81]:
results

0    1    2
0    Yes  Yes   No
1     No  Yes  Yes
2     No   No  Yes
3     No   No  Yes
4     No   No  Yes
..   ...  ...  ...
104  Yes  Yes  Yes
105  Yes   No  Yes
106  Yes  Yes  Yes
107  Yes   No  Yes
108  Yes  Yes  Yes

[109 rows x 3 columns]

In [85]:
correct = results.loc[(results[0] == 'Yes') & (results[1] == 'Yes') & (results[2] == 'Yes')]

In [86]:
correct.count()

0    37
1    37
2    37
dtype: int64